# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de0301c7c8a1744620e9fdec2d9b0415f708bcbf53c239246c9704d05f58db3a9cd265ecdd30c46446f5e31715cfaef8be7587b9d43ff153d00766ff8ba4bd0

test:
  secret_key_base: 4b1027828d9825e0690150aad21c13a2d3e221d3a392e1e638d37601c5c1b10db1be981b6d742fac80843016506b210d8ae833a5dcdf75ab42085f1771020e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
